### ISSUE TITLE
garage job for ambulance and police

### ISSUE THREAD

**Issue by rheiatia** [Mono-94/mono_garage_old#16]
job police and ambulance where you can pick up vehicles, which you set in the config file
example:

Config.JobVehicles = {
    ['police'] = {
                        'police1',
                        'police2'

},

Config.JobGarage= {
    ['police'] = {
        locations = {
            ['Police Garage'] = {
                access = " coords"
                spawn = "coords"
            }
        }
    },

**Comment by Mono-94** [comment]
probably in some update add this.

**Comment by KostaZx** [comment]
> probably in some update add this.

still no update about this?

**Comment by Mono-94** [comment]
Try the latest version I added this function !
