### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by benzon** [Mono-94/mono_garage_old#2]
Hey,
Think you should look in to this bleep thing.

Dont think a loop should be used, it's wasted performance, and since you use ESX, you should listen for job changes insted.

Think you should rethink this, so it dos not use performance with out a reason.

None job blips should only be registered once, and jobs related blips can be drawn/deleted, when job is changed, listen for esx:setJob insted.

https://github.com/Mono-94/sy_garage/blob/4c6d8c63a88e3af3198240dce3a769dbf6d79ef8/client/garage.lua#L25

**Comment by Mono-94** [comment]
I will keep it in mind, when it starts to clean the code I will optimize this part. Thank you very much for the touch

**Comment by Mono-94** [comment]
Deleted thread !
