### ISSUE TITLE
Crashing while trying to open garage

### ISSUE THREAD

**Issue by ic3d00** [Mono-94/mono_garage_old#3]
![image](https://user-images.githubusercontent.com/65400214/234149533-db26244a-ac54-4e2d-8296-ac2e71404734.png)

**Comment by NitroX28** [comment]
I have the same problem mate
tell me if you find something
😞

**Comment by Mono-94** [comment]
Try using a build higher than 2699.

**Comment by Gametake** [comment]
if you use 2699 and not working try uper version

**Comment by Mono-94** [comment]
put this in your server.cfg 
set sv_enforceGameBuild 2802
