### ISSUE TITLE
ox_lib missing export?

### ISSUE THREAD

**Issue by haikoneko** [Mono-94/mono_garage_old#4]
Getting this error on the new update, my ox_lib is up to date and I'm not sure why its doing this

![image](https://user-images.githubusercontent.com/92796928/234424334-58e69cff-7437-47df-92b1-bf2d3e83830d.png)

**Comment by Mono-94** [comment]
Yes I have seen this, but everything seems to be correct, I will check if ox_lib updated something.

**Comment by haikoneko** [comment]
yea its weird, the docs on ox_lib state that the export should be in there and I cant find any files in there about the radial menu

**Comment by Mono-94** [comment]
solved
