### ISSUE TITLE
[SUGGESTION] Realistic Parking Mode (Cars)

### ISSUE THREAD

**Issue by ENC4YP7ED** [Mono-94/mono_garage_old#9]
Add a Realistic Mode 

What should be the realistic mode you might ask I tell you what I mean by that :

1: Add the Ability to Park vehicles on parking lots like all arround the map 

2: The Vehicles should stay there after Server restart and no Garage NPC is needed because all the bought vehicles need to get 
    parked a parking lot and if they not parked on a parking lot location and the server restarts they should get to the impound.
    
3: Add a Marker for every Car that is owned by you like in GTA Online but let us configure the blip in the config.

I hope you understand what I mean with that and would be happy if you could add this.

*edit : I also will add a map for slots to park but this takes time

**Comment by newbialywhodis** [comment]
The way it works for now (saving car wherever the car is) is more realistic

**Comment by ENC4YP7ED** [comment]
> The way it works for now (saving car wherever the car is) is more realistic

Sure but than there is no use of the parkinglots all over the map

**Comment by newbialywhodis** [comment]
The you should change mentality of your players - or use it for roleplay (police impounding)

**Comment by ENC4YP7ED** [comment]
> The you should change mentality of your players - or use it for roleplay (police impounding)

Sure but than there sould be an option to toggle that via config if payment is needed or not

**Comment by newbialywhodis** [comment]
Yup, i have recommended it for Mono to allow Cop to set impound price, we’ll see

**Comment by ENC4YP7ED** [comment]
> Yup, i have recommended it for Mono to allow Cop to set impound price, we’ll see

sure

**Comment by Mono-94** [comment]
I don't want to make this parking realistic, I just like the persistence of the vehicles when spawning the player.
